{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opendkim.serviceAccountName" . }}
  labels:
{{ include "opendkim.labels" . | nindent 4 }}
{{- end -}}
